### ISSUE TITLE
Do not instantiate the logger twice

### ISSUE THREAD

**Issue by mcollina** [fastify/gh-issues-finder#21]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

-

### Node.js version

-

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

In https://github.com/fastify/gh-issues-finder/blob/851dadd6acfdaf76907431c1603471f3a99fbbb1/index.js#L6-L8 we instatiate the logger twice

### Steps to Reproduce

all the time

**Comment by Fdawgs** [comment]
closed by #22
